apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  labels:
    appname: vm-dvtemplate-odr-regional
  name: sample-vm
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - name: cloudinit
            disk: {}
          interfaces:
          - macAddress: 02:69:36:00:00:00
            bridge: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory: 256Mi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: my-public-key
          propagationMethod:
            configDrive: {}
      volumes:
      - persistentVolumeClaim:
          claimName: sample-vm-pvc
        name: rootdisk
      - name: cloudinit
        cloudInitConfigDrive:
          userData: |
            #!/bin/sh
            echo "Running user-data script"
  dataVolumeTemplates:
  - metadata:
      name: sample-vm-pvc
      annotations:
        cdi.kubevirt.io/storage.checkStaticVolume: "true"
      labels:
        appname: vm-dvtemplate-odr-regional
    spec:
      storage:
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 128Mi
      source:
        registry:
          url: "docker://quay.io/nirsof/cirros:0.6.2-1"
