---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: ramen-data-volume-template
    apps.open-cluster-management.io/github-path: vm-dvtemplate-odr-regional
  name: kubevirt-sub
spec:
    channel: kubevirt-samples/kubevirt-gitops
    placement:
      placementRef:
        kind: Placement
        name: kubevirt-placement
