apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: sample-vm-pvc
  labels:
    appname: vm-standalone-dv-odr-regional
spec:
  storage:
    storageClassName: rook-ceph-block
    resources:
      requests:
        storage: 128Mi
  source:
    registry:
      url: "docker://quay.io/nirsof/cirros:0.6.2-1"
