---
apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: cirros-source
spec:
  source:
    registry:
      # Image customized for ramen testing.
      # TODO: Consume from ramendr repo when available.
      url: "docker://host.minikube.internal:5000/nirsof/cirros:0.6.2-1"
